# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 052bb363642d1a9f8b000c5da0e4532b9ee1e392d7cf28f83d18a80361020e6709c72628a29dabcbb11cfdef79626148b342c8186d32df265c9a8979e68011ca

test:
  secret_key_base: d4c3a5faf642b2cdd69128540b7b3f4a4dc3393f583e1ecdf4db742f694ec2b8f9ff0c3cc52743e2136e708a0d023d780428e2dfa49657684357885dddd64915

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
